name: proj
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_circular_chart: ^0.1.0
  http: ^0.12.0
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2

  firebase_core: 0.4.0+8
  firebase_analytics: 4.0.2
  firebase_database: 3.0.5
  cloud_firestore: 0.12.8+1

  firebase_auth: 0.13.0
  google_sign_in: 4.0.4

  rxdart: 0.22.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/Tier-2.png
  - assets/Tier-3.png
  - assets/Tier-4.png
  - assets/Tier-5.png
  - assets/Health_icon_2.png
  - assets/Armor_icon_2.png
  - assets/DPS-icon.png
  - assets/bfsword.png
  - assets/bladeoftheruinedking.png
  - assets/bloodthirster.png
  - assets/chainvest.png
  - assets/cursedblade.png
  - assets/darkin.png
  - assets/dragonsclaw.png
  - assets/forceofnature.png
  - assets/frozenheart.png
  - assets/frozenmallet.png
  - assets/giantsbelt.png
  - assets/guardianangel.png
  - assets/guinsoosrageblade.png
  - assets/hextechgunblade.png
  - assets/hush.png
  - assets/infinityedge.png
  - assets/ionicspark.png
  - assets/knightsvow.png
  - assets/locketoftheironsolari.png
  - assets/ludensecho.png
  - assets/morellonomicon.png
  - assets/needlesslylargerod.png
  - assets/negatroncloak.png
  - assets/phantomdancer.png
  - assets/rabadonsdeathcap.png
  - assets/rapidfirecannon.png
  - assets/recurvebow.png
  - assets/redbuff.png
  - assets/redemption.png
  - assets/runaanshurricane.png
  - assets/seraphsembrace.png
  - assets/spatula.png
  - assets/spearofshojin.png
  - assets/statikkshiv.png
  - assets/swordbreaker.png
  - assets/swordofthedivine.png
  - assets/tearofthegoddess.png
  - assets/thornmail.png
  - assets/titanichydra.png
  - assets/warmogsarmor.png
  - assets/youmuusghostblade.png
  - assets/yuumi.png
  - assets/zekesherald.png
  - assets/zephyr.png
  - assets/sparringgloves.png
  - assets/deathblade.png
  - assets/giantslayer.png
  - assets/repeatingcrossbow.png
  - assets/handofjustice.png
  - assets/iceborngauntlet.png
  - assets/quicksilver.png
  - assets/mittens.png
  - assets/thiefsgloves.png
  - assets/trapclaw.png
  - assets/jeweledgauntlet.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
